### ISSUE TITLE
KM-Bus interface based on ESP32 and Tasmota

### ISSUE THREAD

**Issue by FransOv** [dumpfheimer/WiFiVitotrol#2]
I'm trying to create an interface between the Vitocal KM-Bus and Home Assistant based on ESP32 with Tasmota. Thanks to your project and the discussions on openv I managed to read the traffic on the KM-Bus. I would rather use the Expansion unit than the Vitotrol to emulate for sending information to the Vitotronic. I don't know how the heatpump will react to an extra heating circuit and the expansion unit seems less critical as it is mainly a bridge for other KM-Bus subscribers. The problem is that I don't know the ID to send in response to the prompt from the Vitotronic. It sends this prompt 0400330A1201F808500F when I define the expansion unit in the installation definition. So it is device class 04 and sub-class 12 and requests 8 bytes as ID. I noticed that you use as ID of the Vititrol 11 38 00 11 31. Where did you find this and can I find/construct the ID of the extension unit in a similar way? The openv documentation states that the ID2 of the extension unit  is 0x11 0x12.
<img width="286" alt="image" src="https://github.com/dumpfheimer/WiFiVitotrol/assets/57999223/9c623853-e80e-4dc0-b817-709e80966c32">

**Comment by dumpfheimer** [comment]
Sorry for the late repla, it seems like I need to check my notification settings.
Have you resolved your issue?
I had to brute force the IDs and check if something comes back. It is painful =) I do know two devices, thogh:
// vitotrol 200
#define DEVICE_ID 0x34
#define DEVICE_SN1 0x00
#define DEVICE_SN2 0x05
#define DEVICE_SLOT 0x01

// vitotrol 300
#define DEVICE_ID 0x38
#define DEVICE_SN1 0x00
#define DEVICE_SN2 0x11
#define DEVICE_SLOT 0x02

Does this help?

**Comment by FransOv** [comment]
Thanks you for the information. I decided not to proceed with the KM Bus interface but go with the Optolink interface as implemented by https://github.com/philippoo66/optolink-splitter/wiki.
This provided me with a very detailed info and control of the heatpump. Although it took some effort to find the relevant parameter addresses. 
![Screenshot_20241113_110652_Home Assistant](https://github.com/user-attachments/assets/c8d7dff2-94ce-4dde-8666-bb5c05be88c9)

**Comment by meks007** [comment]
Frans, not wanting to hijack this issue, but I've also set up an optolink-splitter and I'm currently trying to get about the same image you just posted. Would you mind sharing the datapoints you used to get all the values? I guess I can then map your datapoints from your 300-G to my 222-A using the datapoint lists,

**Comment by FransOv** [comment]
The Excel file at https://github.com/philippoo66/optolink-splitter/wiki/310-Parameter-Addresses contains all addresses that I use.

**Comment by meks007** [comment]
Yes, it's the same Excel file I use for getting the datapoints. I'm having difficulty finding all relevant datapoints in that Excel. It would help tremendously if you could share the exact datapoints you used to create that chart. Like, for example, I'm struggling to get the EV value (28% in your picture). If I knew what datapoint you used to get that value, I could then check if it's the same for the 222-A and map it to my heat pump in case it's different - mapping is a lot easier than trying to find the needle in a haystack.

**Comment by FransOv** [comment]
The full list of the datapoints I use is in https://github.com/philippoo66/optolink-splitter/wiki/210-Home-Assitant-Integration-of-Optolink%E2%80%90Splitter

**Comment by meks007** [comment]
danke!!

**Comment by FransOv** [comment]
Please continue on https://github.com/philippoo66/optolink-splitter if needed so is not to clutter this site with comments that have nothing to do with it.
